version: 2.1
orbs:
  node: circleci/node@4.1.0
  eb: circleci/aws-elastic-beanstalk@1.0.0
  aws-cli: circleci/aws-cli@2.0.2
# Define the jobs we want to run for this project  
jobs:
  build:
    # Limit to main branch
    filters:
      branches:
         only:
            - main
    docker:
      - image: "cimg/node:14.19" # Use NodeJS version 14.19 to be compatible with elastic beanstalk NodeJS
    steps:
      - checkout
      - run: node --version
      - aws-cli/setup
      - eb/setup
      # Install front-end and back-end
      - run:
          name: Front-end install
          command: npm run frontend:install
      - run:
          name: Back-end install
          command: npm run backend:install
      # Build front-end and back-end
      - run:
          name: Front-end build
          command: npm run frontend:build
      - run:
          name: Back-end build
          command: npm run backend:build
      # Deploy front-end to S3 bucket and back-end to Elastic Beanstalk
      - run:
          name: Back-end deploy
          command: npm run backend:deploy
      - run:
          name: Front-end deploy
          command: npm run frontend:deploy
